name: Deploy on Tag

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Debug
        run: |
            ls -la

      - name: Debug SSH Key
        run: |
          echo "SSH_PRIVATE_KEY: ***"
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          cat private_key.pem
          ssh-keygen -y -f private_key.pem
        shell: bash

      - name: Copia archivos
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 'userprod-b1.deliver.ar'
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/home/ubuntu/nrelease'
