name: Deploy on Tag

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Debug
        run: |
            ls -la

      - name: Debug Secret
        run: |
            echo "SSH_PRIVATE_KEY is present"
            echo "$SSH_PRIVATE_KEY" | cat
            echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
            echo "$SSH_PRIVATE_KEY" | ssh-keygen -y -f -
            shell: /usr/bin/bash -e {0}

            
      - name: Copia archivos
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 'userprod-b1.deliver.ar'
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/home/ubuntu/nrelease'
