name: Deploy on Tag

on:
  push:
    tags:
      - 'UserAProd*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        

      - name: Debug
        run: |
          ls -la
          pwd
          
      - name: Debug SSH
        run: ssh -i <(echo "$SSH_PRIVATE_KEY") ubuntu@userprod-b1.deliver.ar "ls -la /home/ubuntu/nrelease"

            
      - name: Copia archivos
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 'userprod-b1.deliver.ar'
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/home/ubuntu/nrelease'
